### ISSUE TITLE
Amount incorrect and CC declined

### ISSUE THREAD

**Issue by mambolina** [moonstonemedia/WP-Simple-Pay-Lite-for-Stripe#30]
I am using the WP Simple Pay Lite for Stripe plugin on my website to process payments. I'm in test mode. The amount to be paid is incorrect. When the amount is $100 the plugin shows $1, when it's $150 it shows $1.5

$100 Gift Certificate [stripe name="Photography" description="Gift Certificate" amount="100.00" billing="true" shipping="true"]

It also keeps on saying the credit card has been declined (I have used 2 different cards and both get a message of declined)

Please advise.

**Comment by nickyoung87** [comment]
@mambolina

The issue is coming with how you are adding your `amount` attribute. The amount needs to be declared in the total number of cents for it to work properly - so Stripe is reading yours as 100.00 cents. To make it $100 you would want it to look like this: `amount="10000"`

For the other issue, since you are in test mode it will not accept normal credit cards. Instead you will want to use one of the cards setup as test cards by Stripe: https://stripe.com/docs/testing#cards

Hope that helps!

**Comment by mambolina** [comment]
Thanks so much!

**Comment by nickyoung87** [comment]
No problem at all glad it's working for you now!
